# Generated by Django 6.1 on 2026-09-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='telegram_sent',
            new_name='whatsapp_sent',
        ),
    ]
