# Generated by Django 6.1 on 2026-09-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_telegram_sent_contactmessage_whatsapp_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='whatsapp_sent',
            new_name='telegram_sent',
        ),
    ]
