# Generated by Django 6.1 on 2026-09-03 08:09

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_whatsapp_sent_contactmessage_telegram_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[portfolio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', validators=[portfolio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='resume/', validators=[portfolio.models.validate_resume_file]),
        ),
    ]
