# Generated by Django 6.1 on 2026-09-05 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_profile_profile_image_alter_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='telegram_sent',
            new_name='email_sent',
        ),
        migrations.CreateModel(
            name='ResumeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('contact_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_downloads', to='portfolio.contactmessage')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='portfolio.resume')),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
