# Generated by Django 6.1 on 2026-09-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_rename_telegram_sent_contactmessage_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='skills',
            field=models.TextField(default='', help_text='Enter skills separated by commas. Example: Python, SQL, JavaScript'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='title',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
