# Generated by Django 6.1 on 2026-09-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_skill_options_remove_skill_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, help_text='Example: In Progress, Completed', max_length=100)),
                ('topics', models.TextField(help_text='Enter topics separated by commas. Example: Python, Django, REST API, HTML, CSS')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
